### ISSUE TITLE
Chrome自动关闭

### ISSUE THREAD

**Issue by sunnymyl** [01miaom/jiankangyizhan#19]
~ % python3 10.py
欢迎使用ddddocr，本项目专注带动行业内卷，个人博客:wenanzhe.com
训练数据支持来源于:http://146.56.204.113:19199/preview
爬虫框架feapder可快速一键接入，快速开启爬虫之旅：https://github.com/Boris-code/feapder
阻tm
Traceback (most recent call last):
  File "10.py", line 50, in <module>
    browser.find_element_by_id('btn_login').click()
  File "/Users/adam/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/adam/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "/Users/adam/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/Users/adam/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button type="button" class="Btn-l mb15" id="btn_login">...</button> is not clickable at point (600, 519). Other element would receive the click: <div id="loginNotice" class="mask"></div>
  (Session info: chrome=100.0.4896.127)
Stacktrace:
0   chromedriver                        0x00000001024d03d9 chromedriver + 5104601
1   chromedriver                        0x0000000102460bf3 chromedriver + 4647923
2   chromedriver                        0x0000000102051b48 chromedriver + 392008
3   chromedriver                        0x000000010208e3c1 chromedriver + 639937
4   chromedriver                        0x000000010208bfa9 chromedriver + 630697
5   chromedriver                        0x0000000102089674 chromedriver + 620148
6   chromedriver                        0x0000000102088432 chromedriver + 615474
7   chromedriver                        0x000000010207bd79 chromedriver + 564601
8   chromedriver                        0x00000001020a46c2 chromedriver + 730818
9   chromedriver                        0x000000010207b635 chromedriver + 562741
10  chromedriver                        0x00000001020a47ce chromedriver + 731086
11  chromedriver                        0x00000001020b7091 chromedriver + 807057
12  chromedriver                        0x00000001020a45b3 chromedriver + 730547
13  chromedriver                        0x000000010207a139 chromedriver + 557369
14  chromedriver                        0x000000010207b165 chromedriver + 561509
15  chromedriver                        0x000000010248f39d chromedriver + 4838301
16  chromedriver                        0x00000001024a7cde chromedriver + 4938974
17  chromedriver                        0x00000001024acb5e chromedriver + 4959070
18  chromedriver                        0x00000001024a894a chromedriver + 4942154
19  chromedriver                        0x000000010248433c chromedriver + 4793148
20  chromedriver                        0x00000001024c23b8 chromedriver + 5047224
21  chromedriver                        0x00000001024c253f chromedriver + 5047615
22  chromedriver                        0x00000001024d7705 chromedriver + 5134085
23  libsystem_pthread.dylib             0x00007ff81d3364e1 _pthread_start + 125
24  libsystem_pthread.dylib             0x00007ff81d331f6b thread_start + 15

**Comment by sunnymyl** [comment]
验证码screen shot不对，弹窗没有关闭

**Comment by slsl00** [comment]
我也有同樣問題
