### ISSUE TITLE
验证码识别不准

### ISSUE THREAD

**Issue by xhk777** [01miaom/jiankangyizhan#3]
大部分验证码都是识别错误的...

**Comment by 01miaom** [comment]
为了省事用的是ddddocr的开源项目，训练样本较小。可以把那部分代码替换成准确率更高的api，例如百度ai开放平台的文字识别: https://ai.baidu.com/tech/ocr

**Comment by xhk777** [comment]
赞！

**Comment by androidcn** [comment]
> 

谢谢

**Comment by xhk777** [comment]
刚刚用了百度的文字识别，也是不准的哈哈

**Comment by 01miaom** [comment]
我在代码中加入了灰度和降噪算法，识别准确率有了较大的提升。如果仍然遇到问题的话，可以考虑重复执行验证码填写的部分，降低失败概率。

**Comment by androidcn** [comment]
> 为了省事用的是ddddocr的开源项目，不是很适用于验证码识别。可以把那部分代码替换成准确率更高的api，例如百度ai开放平台的文字识别: [ai.baidu.com/tech/ocr](https://ai.baidu.com/tech/ocr) 我也会在之后的版本中改善这一点。

这可写多一个 百毒的版本吗？谢谢

**Comment by 01miaom** [comment]
> > 为了省事用的是ddddocr的开源项目，不是很适用于验证码识别。可以把那部分代码替换成准确率更高的api，例如百度ai开放平台的文字识别: [ai.baidu.com/tech/ocr](https://ai.baidu.com/tech/ocr) 我也会在之后的版本中改善这一点。
> 
> 可以写多一个 百毒的版本吗？谢谢

我之后会尝试加入百度api，但是鉴于验证码识别准确率在上一个版本中已经有了大幅提高，而且百度api的准确率没有想象的那么高。所以更换api带来的准确率提升可能非常有限。

**Comment by androidcn** [comment]
> > > 为了省事用的是ddddocr的开源项目，不是很适用于验证码识别。可以把那部分代码替换成准确率更高的api，例如百度ai开放平台的文字识别: [ai.baidu.com/tech/ocr](https://ai.baidu.com/tech/ocr) 我也会在之后的版本中改善这一点。
> > 
> > 
> > 可以写多一个 百毒的版本吗？谢谢
> 
> 我之后会尝试加入百度api，但是鉴于验证码识别准确率在上一个版本中已经有了大幅提高，而且百度api的准确率没有想象的那么高。所以更换api带来的准确率提升可能非常有限。

直是奇怪，Intel Macbook 装 pip install ddddocr 也是出错
M1 macbook也是出错

**Comment by NG-zoro** [comment]
不是，登录的时候人工输入不就Ok了？这个脚本的重点又不在这

**Comment by guoty1991** [comment]
Traceback (most recent call last):
  File "C:/Users/Steve/Desktop/jiankangyizhan-main/jiankangyizhan-main/main.py", line 33, in <module>
    im = Image.open('spider/screenshot.png')
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'spider/screenshot.png'

请问运行的时候出现这个问题是因为验证码识别不到造成的吗？

**Comment by guoty1991** [comment]
> 

这个问题解决了是因为没有建spider 文件夹。但是保存下来的code.pnd 截图都是密码两个字而不是验证码的截图。所以验证码总是识别失败。

**Comment by androidcn** [comment]
> 不是，登录的时候人工输入不就Ok了？这个脚本的重点又不在这

重点是 快速登录后，第二页面的提交

**Comment by guoty1991** [comment]
> > 不是，登录的时候人工输入不就Ok了？这个脚本的重点又不在这
> 
> 重点是 快速登录后，第二页面的提交

恩恩 之前没有玩过这类脚本，大概明白意思了。
