### ISSUE TITLE
Traceback (most recent call last):   File "main.py", line 65, in <module>     timeArray=time.localtime(int(data[149:162])) OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by qingtong1215** [01miaom/jiankangyizhan#5]
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    timeArray=time.localtime(int(data[149:162]))
OSError: [Errno 22] Invalid argument
你好，感谢你的分享，我运行代码的时候提示了这个，是因为时间没有到10点么？
我目前已经可以识别验证码并进去预约界面了。
期待您的回复

**Comment by 01miaom** [comment]
这可能是请求淘宝授时api出现错误，目前还没有定位到原因。可以尝试去掉这部分代码并改成直接调用系统时间。
`import time
timeArray=time.time()`

**Comment by qingtong1215** [comment]
谢谢你的回复，我修改后提示了这个
[45652:51676:0217/132634.686:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is
这是因为预约接口关闭的原因才报错么。
还有一个问题是，这个程序可以9点50分就运行程序么，它会自己识别10点到了然后进行操作。

**Comment by 01miaom** [comment]
1. 这似乎是在Chrome某个版本中出现的错误，可以参考这个链接来解决[](https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled)

2. 是的，代码可以检测时间，到十点钟会
自动运行
